"""Initial tables

Revision ID: 6706e4bf3cc5
Revises: 
Create Date: 2026-05-26 14:00:31.585312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6706e4bf3cc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters_meta',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('blob_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_meta_blob_key'), 'characters_meta', ['blob_key'], unique=True)
    op.create_index(op.f('ix_characters_meta_id'), 'characters_meta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_meta_id'), table_name='characters_meta')
    op.drop_index(op.f('ix_characters_meta_blob_key'), table_name='characters_meta')
    op.drop_table('characters_meta')
    # ### end Alembic commands ###
